// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: github.com/dogmatiq/dapper/internal/fixtures/protostub.proto

package fixtures

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Enum int32

const (
	Enum_UNKNOWN Enum = 0
	Enum_FOO     Enum = 1
	Enum_BAR     Enum = 2
)

// Enum value maps for Enum.
var (
	Enum_name = map[int32]string{
		0: "UNKNOWN",
		1: "FOO",
		2: "BAR",
	}
	Enum_value = map[string]int32{
		"UNKNOWN": 0,
		"FOO":     1,
		"BAR":     2,
	}
)

func (x Enum) Enum() *Enum {
	p := new(Enum)
	*p = x
	return p
}

func (x Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_enumTypes[0].Descriptor()
}

func (Enum) Type() protoreflect.EnumType {
	return &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_enumTypes[0]
}

func (x Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Enum.Descriptor instead.
func (Enum) EnumDescriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstField string  `protobuf:"bytes,1,opt,name=first_field,json=firstField,proto3" json:"first_field,omitempty"`
	EnumField  Enum    `protobuf:"varint,2,opt,name=enum_field,json=enumField,proto3,enum=dogmatiq.dapper.fixtures.Enum" json:"enum_field,omitempty"`
	Nested     *Nested `protobuf:"bytes,3,opt,name=nested,proto3" json:"nested,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetFirstField() string {
	if x != nil {
		return x.FirstField
	}
	return ""
}

func (x *Message) GetEnumField() Enum {
	if x != nil {
		return x.EnumField
	}
	return Enum_UNKNOWN
}

func (x *Message) GetNested() *Nested {
	if x != nil {
		return x.Nested
	}
	return nil
}

type Nested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NestedFirstField  string `protobuf:"bytes,1,opt,name=nested_first_field,json=nestedFirstField,proto3" json:"nested_first_field,omitempty"`
	NestedSecondField bool   `protobuf:"varint,2,opt,name=nested_second_field,json=nestedSecondField,proto3" json:"nested_second_field,omitempty"`
}

func (x *Nested) Reset() {
	*x = Nested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested) ProtoMessage() {}

func (x *Nested) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested.ProtoReflect.Descriptor instead.
func (*Nested) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescGZIP(), []int{1}
}

func (x *Nested) GetNestedFirstField() string {
	if x != nil {
		return x.NestedFirstField
	}
	return ""
}

func (x *Nested) GetNestedSecondField() bool {
	if x != nil {
		return x.NestedSecondField
	}
	return false
}

var File_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto protoreflect.FileDescriptor

var file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDesc = []byte{
	0x0a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x67,
	0x6d, 0x61, 0x74, 0x69, 0x71, 0x2f, 0x64, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x74, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18,
	0x64, 0x6f, 0x67, 0x6d, 0x61, 0x74, 0x69, 0x71, 0x2e, 0x64, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e,
	0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0xa3, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x3d, 0x0a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x64, 0x6f, 0x67, 0x6d,
	0x61, 0x74, 0x69, 0x71, 0x2e, 0x64, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x66, 0x69, 0x78, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x09, 0x65, 0x6e, 0x75, 0x6d, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x38, 0x0a, 0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x6f, 0x67, 0x6d, 0x61, 0x74, 0x69, 0x71, 0x2e,
	0x64, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e,
	0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x52, 0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x22, 0x66,
	0x0a, 0x06, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x6e, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x5f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x46, 0x69, 0x72, 0x73,
	0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x11, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x2a, 0x25, 0x0a, 0x04, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x46,
	0x4f, 0x4f, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x41, 0x52, 0x10, 0x02, 0x42, 0x2e, 0x5a,
	0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x67, 0x6d,
	0x61, 0x74, 0x69, 0x71, 0x2f, 0x64, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescData = file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDesc
)

func file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescData)
	})
	return file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescData
}

var file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_goTypes = []interface{}{
	(Enum)(0),       // 0: dogmatiq.dapper.fixtures.Enum
	(*Message)(nil), // 1: dogmatiq.dapper.fixtures.Message
	(*Nested)(nil),  // 2: dogmatiq.dapper.fixtures.Nested
}
var file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_depIdxs = []int32{
	0, // 0: dogmatiq.dapper.fixtures.Message.enum_field:type_name -> dogmatiq.dapper.fixtures.Enum
	2, // 1: dogmatiq.dapper.fixtures.Message.nested:type_name -> dogmatiq.dapper.fixtures.Nested
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_init() }
func file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_init() {
	if File_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_depIdxs,
		EnumInfos:         file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_enumTypes,
		MessageInfos:      file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto = out.File
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDesc = nil
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_goTypes = nil
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_depIdxs = nil
}
