// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: github.com/dogmatiq/dapper/internal/fixtures/protostub.proto

package fixtures

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protoenum int32

const (
	Protoenum_UNKNOWN Protoenum = 0
	Protoenum_FOO     Protoenum = 1
	Protoenum_BAR     Protoenum = 2
)

// Enum value maps for Protoenum.
var (
	Protoenum_name = map[int32]string{
		0: "UNKNOWN",
		1: "FOO",
		2: "BAR",
	}
	Protoenum_value = map[string]int32{
		"UNKNOWN": 0,
		"FOO":     1,
		"BAR":     2,
	}
)

func (x Protoenum) Enum() *Protoenum {
	p := new(Protoenum)
	*p = x
	return p
}

func (x Protoenum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protoenum) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_enumTypes[0].Descriptor()
}

func (Protoenum) Type() protoreflect.EnumType {
	return &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_enumTypes[0]
}

func (x Protoenum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protoenum.Descriptor instead.
func (Protoenum) EnumDescriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescGZIP(), []int{0}
}

type Protostub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstField   string          `protobuf:"bytes,1,opt,name=first_field,json=firstField,proto3" json:"first_field,omitempty"`
	EnumField    Protoenum       `protobuf:"varint,2,opt,name=enum_field,json=enumField,proto3,enum=dogmatiq.dapper.fixtures.Protoenum" json:"enum_field,omitempty"`
	InnerMessage *ProtostubInner `protobuf:"bytes,3,opt,name=inner_message,json=innerMessage,proto3" json:"inner_message,omitempty"`
}

func (x *Protostub) Reset() {
	*x = Protostub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Protostub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Protostub) ProtoMessage() {}

func (x *Protostub) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Protostub.ProtoReflect.Descriptor instead.
func (*Protostub) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescGZIP(), []int{0}
}

func (x *Protostub) GetFirstField() string {
	if x != nil {
		return x.FirstField
	}
	return ""
}

func (x *Protostub) GetEnumField() Protoenum {
	if x != nil {
		return x.EnumField
	}
	return Protoenum_UNKNOWN
}

func (x *Protostub) GetInnerMessage() *ProtostubInner {
	if x != nil {
		return x.InnerMessage
	}
	return nil
}

type ProtostubInner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InnerFirstField  string `protobuf:"bytes,1,opt,name=inner_first_field,json=innerFirstField,proto3" json:"inner_first_field,omitempty"`
	InnerSecondField bool   `protobuf:"varint,2,opt,name=inner_second_field,json=innerSecondField,proto3" json:"inner_second_field,omitempty"`
}

func (x *ProtostubInner) Reset() {
	*x = ProtostubInner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtostubInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtostubInner) ProtoMessage() {}

func (x *ProtostubInner) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtostubInner.ProtoReflect.Descriptor instead.
func (*ProtostubInner) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescGZIP(), []int{1}
}

func (x *ProtostubInner) GetInnerFirstField() string {
	if x != nil {
		return x.InnerFirstField
	}
	return ""
}

func (x *ProtostubInner) GetInnerSecondField() bool {
	if x != nil {
		return x.InnerSecondField
	}
	return false
}

var File_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto protoreflect.FileDescriptor

var file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDesc = []byte{
	0x0a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x67,
	0x6d, 0x61, 0x74, 0x69, 0x71, 0x2f, 0x64, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x74, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18,
	0x64, 0x6f, 0x67, 0x6d, 0x61, 0x74, 0x69, 0x71, 0x2e, 0x64, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e,
	0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0xbf, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x74, 0x75, 0x62, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x42, 0x0a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x5f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x64, 0x6f,
	0x67, 0x6d, 0x61, 0x74, 0x69, 0x71, 0x2e, 0x64, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x66, 0x69,
	0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x65, 0x6e, 0x75, 0x6d,
	0x52, 0x09, 0x65, 0x6e, 0x75, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x4d, 0x0a, 0x0d, 0x69,
	0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x64, 0x6f, 0x67, 0x6d, 0x61, 0x74, 0x69, 0x71, 0x2e, 0x64, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x2e, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x74, 0x75, 0x62, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x0c, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x6a, 0x0a, 0x0e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x74, 0x75, 0x62, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x11,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x46, 0x69,
	0x72, 0x73, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x2a, 0x2a, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x65,
	0x6e, 0x75, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x46, 0x4f, 0x4f, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x41, 0x52,
	0x10, 0x02, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x6f, 0x67, 0x6d, 0x61, 0x74, 0x69, 0x71, 0x2f, 0x64, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescData = file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDesc
)

func file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescData)
	})
	return file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescData
}

var file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_goTypes = []interface{}{
	(Protoenum)(0),         // 0: dogmatiq.dapper.fixtures.Protoenum
	(*Protostub)(nil),      // 1: dogmatiq.dapper.fixtures.Protostub
	(*ProtostubInner)(nil), // 2: dogmatiq.dapper.fixtures.ProtostubInner
}
var file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_depIdxs = []int32{
	0, // 0: dogmatiq.dapper.fixtures.Protostub.enum_field:type_name -> dogmatiq.dapper.fixtures.Protoenum
	2, // 1: dogmatiq.dapper.fixtures.Protostub.inner_message:type_name -> dogmatiq.dapper.fixtures.ProtostubInner
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_init() }
func file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_init() {
	if File_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Protostub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtostubInner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_depIdxs,
		EnumInfos:         file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_enumTypes,
		MessageInfos:      file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto = out.File
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDesc = nil
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_goTypes = nil
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_depIdxs = nil
}
