// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: github.com/dogmatiq/dapper/internal/fixtures/protoeditions.proto

package fixtures

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumEditions int32

const (
	EnumEditions_UNKNOWN_EDITIONS EnumEditions = 0
	EnumEditions_FOO_EDITIONS     EnumEditions = 1
	EnumEditions_BAR_EDITIONS     EnumEditions = 2
)

// Enum value maps for EnumEditions.
var (
	EnumEditions_name = map[int32]string{
		0: "UNKNOWN_EDITIONS",
		1: "FOO_EDITIONS",
		2: "BAR_EDITIONS",
	}
	EnumEditions_value = map[string]int32{
		"UNKNOWN_EDITIONS": 0,
		"FOO_EDITIONS":     1,
		"BAR_EDITIONS":     2,
	}
)

func (x EnumEditions) Enum() *EnumEditions {
	p := new(EnumEditions)
	*p = x
	return p
}

func (x EnumEditions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumEditions) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_enumTypes[0].Descriptor()
}

func (EnumEditions) Type() protoreflect.EnumType {
	return &file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_enumTypes[0]
}

func (x EnumEditions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type MessageEditions struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Str         *string                `protobuf:"bytes,1,opt,name=str"`
	xxx_hidden_Enum        EnumEditions           `protobuf:"varint,2,opt,name=enum,enum=dogmatiq.dapper.fixtures.EnumEditions"`
	xxx_hidden_Nested      *NestedEditions        `protobuf:"bytes,3,opt,name=nested"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MessageEditions) Reset() {
	*x = MessageEditions{}
	mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEditions) ProtoMessage() {}

func (x *MessageEditions) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MessageEditions) GetStr() string {
	if x != nil {
		if x.xxx_hidden_Str != nil {
			return *x.xxx_hidden_Str
		}
		return ""
	}
	return ""
}

func (x *MessageEditions) GetEnum() EnumEditions {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Enum
		}
	}
	return EnumEditions_UNKNOWN_EDITIONS
}

func (x *MessageEditions) GetNested() *NestedEditions {
	if x != nil {
		return x.xxx_hidden_Nested
	}
	return nil
}

func (x *MessageEditions) SetStr(v string) {
	x.xxx_hidden_Str = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *MessageEditions) SetEnum(v EnumEditions) {
	x.xxx_hidden_Enum = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *MessageEditions) SetNested(v *NestedEditions) {
	x.xxx_hidden_Nested = v
}

func (x *MessageEditions) HasStr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MessageEditions) HasEnum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MessageEditions) HasNested() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Nested != nil
}

func (x *MessageEditions) ClearStr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Str = nil
}

func (x *MessageEditions) ClearEnum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Enum = EnumEditions_UNKNOWN_EDITIONS
}

func (x *MessageEditions) ClearNested() {
	x.xxx_hidden_Nested = nil
}

type MessageEditions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Str    *string
	Enum   *EnumEditions
	Nested *NestedEditions
}

func (b0 MessageEditions_builder) Build() *MessageEditions {
	m0 := &MessageEditions{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Str != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Str = b.Str
	}
	if b.Enum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Enum = *b.Enum
	}
	x.xxx_hidden_Nested = b.Nested
	return m0
}

type NestedEditions struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_NestedA     *string                `protobuf:"bytes,1,opt,name=nested_a,json=nestedA"`
	xxx_hidden_NestedB     []byte                 `protobuf:"bytes,2,opt,name=nested_b,json=nestedB"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NestedEditions) Reset() {
	*x = NestedEditions{}
	mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedEditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedEditions) ProtoMessage() {}

func (x *NestedEditions) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NestedEditions) GetNestedA() string {
	if x != nil {
		if x.xxx_hidden_NestedA != nil {
			return *x.xxx_hidden_NestedA
		}
		return ""
	}
	return ""
}

func (x *NestedEditions) GetNestedB() []byte {
	if x != nil {
		return x.xxx_hidden_NestedB
	}
	return nil
}

func (x *NestedEditions) SetNestedA(v string) {
	x.xxx_hidden_NestedA = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *NestedEditions) SetNestedB(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_NestedB = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *NestedEditions) HasNestedA() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *NestedEditions) HasNestedB() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *NestedEditions) ClearNestedA() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_NestedA = nil
}

func (x *NestedEditions) ClearNestedB() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NestedB = nil
}

type NestedEditions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	NestedA *string
	NestedB []byte
}

func (b0 NestedEditions_builder) Build() *NestedEditions {
	m0 := &NestedEditions{}
	b, x := &b0, m0
	_, _ = b, x
	if b.NestedA != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_NestedA = b.NestedA
	}
	if b.NestedB != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_NestedB = b.NestedB
	}
	return m0
}

var File_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_rawDesc = "" +
	"\n" +
	"@github.com/dogmatiq/dapper/internal/fixtures/protoeditions.proto\x12\x18dogmatiq.dapper.fixtures\"\xa1\x01\n" +
	"\x0fMessageEditions\x12\x10\n" +
	"\x03str\x18\x01 \x01(\tR\x03str\x12:\n" +
	"\x04enum\x18\x02 \x01(\x0e2&.dogmatiq.dapper.fixtures.EnumEditionsR\x04enum\x12@\n" +
	"\x06nested\x18\x03 \x01(\v2(.dogmatiq.dapper.fixtures.NestedEditionsR\x06nested\"F\n" +
	"\x0eNestedEditions\x12\x19\n" +
	"\bnested_a\x18\x01 \x01(\tR\anestedA\x12\x19\n" +
	"\bnested_b\x18\x02 \x01(\fR\anestedB*H\n" +
	"\fEnumEditions\x12\x14\n" +
	"\x10UNKNOWN_EDITIONS\x10\x00\x12\x10\n" +
	"\fFOO_EDITIONS\x10\x01\x12\x10\n" +
	"\fBAR_EDITIONS\x10\x02B.Z,github.com/dogmatiq/dapper/internal/fixturesb\beditionsp\xe9\a"

var file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_goTypes = []any{
	(EnumEditions)(0),       // 0: dogmatiq.dapper.fixtures.EnumEditions
	(*MessageEditions)(nil), // 1: dogmatiq.dapper.fixtures.MessageEditions
	(*NestedEditions)(nil),  // 2: dogmatiq.dapper.fixtures.NestedEditions
}
var file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_depIdxs = []int32{
	0, // 0: dogmatiq.dapper.fixtures.MessageEditions.enum:type_name -> dogmatiq.dapper.fixtures.EnumEditions
	2, // 1: dogmatiq.dapper.fixtures.MessageEditions.nested:type_name -> dogmatiq.dapper.fixtures.NestedEditions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_init() }
func file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_init() {
	if File_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_rawDesc), len(file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_depIdxs,
		EnumInfos:         file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_enumTypes,
		MessageInfos:      file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto = out.File
	file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_goTypes = nil
	file_github_com_dogmatiq_dapper_internal_fixtures_protoeditions_proto_depIdxs = nil
}
