// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: github.com/dogmatiq/dapper/internal/fixtures/protostub.proto

package fixtures

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Enum int32

const (
	Enum_UNKNOWN Enum = 0
	Enum_FOO     Enum = 1
	Enum_BAR     Enum = 2
)

// Enum value maps for Enum.
var (
	Enum_name = map[int32]string{
		0: "UNKNOWN",
		1: "FOO",
		2: "BAR",
	}
	Enum_value = map[string]int32{
		"UNKNOWN": 0,
		"FOO":     1,
		"BAR":     2,
	}
)

func (x Enum) Enum() *Enum {
	p := new(Enum)
	*p = x
	return p
}

func (x Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_enumTypes[0].Descriptor()
}

func (Enum) Type() protoreflect.EnumType {
	return &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_enumTypes[0]
}

func (x Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Enum.Descriptor instead.
func (Enum) EnumDescriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Str           string                 `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	Enum          Enum                   `protobuf:"varint,2,opt,name=enum,proto3,enum=dogmatiq.dapper.fixtures.Enum" json:"enum,omitempty"`
	Nested        *Nested                `protobuf:"bytes,3,opt,name=nested,proto3" json:"nested,omitempty"`
	Stringer      *Stringer              `protobuf:"bytes,4,opt,name=stringer,proto3" json:"stringer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

func (x *Message) GetEnum() Enum {
	if x != nil {
		return x.Enum
	}
	return Enum_UNKNOWN
}

func (x *Message) GetNested() *Nested {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *Message) GetStringer() *Stringer {
	if x != nil {
		return x.Stringer
	}
	return nil
}

type Nested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NestedA       string                 `protobuf:"bytes,1,opt,name=nested_a,json=nestedA,proto3" json:"nested_a,omitempty"`
	NestedB       []byte                 `protobuf:"bytes,2,opt,name=nested_b,json=nestedB,proto3" json:"nested_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested) Reset() {
	*x = Nested{}
	mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested) ProtoMessage() {}

func (x *Nested) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested.ProtoReflect.Descriptor instead.
func (*Nested) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescGZIP(), []int{1}
}

func (x *Nested) GetNestedA() string {
	if x != nil {
		return x.NestedA
	}
	return ""
}

func (x *Nested) GetNestedB() []byte {
	if x != nil {
		return x.NestedB
	}
	return nil
}

type Stringer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stringer) Reset() {
	*x = Stringer{}
	mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stringer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stringer) ProtoMessage() {}

func (x *Stringer) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stringer.ProtoReflect.Descriptor instead.
func (*Stringer) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescGZIP(), []int{2}
}

func (x *Stringer) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDesc = "" +
	"\n" +
	"<github.com/dogmatiq/dapper/internal/fixtures/protostub.proto\x12\x18dogmatiq.dapper.fixtures\"\xc9\x01\n" +
	"\aMessage\x12\x10\n" +
	"\x03str\x18\x01 \x01(\tR\x03str\x122\n" +
	"\x04enum\x18\x02 \x01(\x0e2\x1e.dogmatiq.dapper.fixtures.EnumR\x04enum\x128\n" +
	"\x06nested\x18\x03 \x01(\v2 .dogmatiq.dapper.fixtures.NestedR\x06nested\x12>\n" +
	"\bstringer\x18\x04 \x01(\v2\".dogmatiq.dapper.fixtures.StringerR\bstringer\">\n" +
	"\x06Nested\x12\x19\n" +
	"\bnested_a\x18\x01 \x01(\tR\anestedA\x12\x19\n" +
	"\bnested_b\x18\x02 \x01(\fR\anestedB\" \n" +
	"\bStringer\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value*%\n" +
	"\x04Enum\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03FOO\x10\x01\x12\a\n" +
	"\x03BAR\x10\x02B.Z,github.com/dogmatiq/dapper/internal/fixturesb\x06proto3"

var (
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescData []byte
)

func file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDesc), len(file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDescData
}

var file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_goTypes = []any{
	(Enum)(0),        // 0: dogmatiq.dapper.fixtures.Enum
	(*Message)(nil),  // 1: dogmatiq.dapper.fixtures.Message
	(*Nested)(nil),   // 2: dogmatiq.dapper.fixtures.Nested
	(*Stringer)(nil), // 3: dogmatiq.dapper.fixtures.Stringer
}
var file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_depIdxs = []int32{
	0, // 0: dogmatiq.dapper.fixtures.Message.enum:type_name -> dogmatiq.dapper.fixtures.Enum
	2, // 1: dogmatiq.dapper.fixtures.Message.nested:type_name -> dogmatiq.dapper.fixtures.Nested
	3, // 2: dogmatiq.dapper.fixtures.Message.stringer:type_name -> dogmatiq.dapper.fixtures.Stringer
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_init() }
func file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_init() {
	if File_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDesc), len(file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_depIdxs,
		EnumInfos:         file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_enumTypes,
		MessageInfos:      file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto = out.File
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_goTypes = nil
	file_github_com_dogmatiq_dapper_internal_fixtures_protostub_proto_depIdxs = nil
}
